apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3cnd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0005-tenant/tkrw-pr712-0075-0005-app/devfile-sample-3cnd@sha256:5ffafbd9b5a36aced03b5a494d91dafb928c0dfe8575e401886701a7a5d9bddb
        name: my-nodejs
        resources: {}
status: {}
